git:
  submodules: false
cache:
  directories:
    - node_modules
env:
  global:
    secure: C3UQt4RiLQWzugbiTzw00lg8+/lCUPK3FjSxck4BnU7+uB3wdh7qaZp88mG/hUrrB5tASW316UowzRCYTItPtsNuEOLK3x+KxKZBW5fpyvaSOZrSlPV7qv1kJjGQirskgZxH1aH/g/fHknBXsifawPT6it63INk/SVE/szfEHfg=
before_install:
- mkdir ci
- cd ci
- git init
- git config user.name "autodeploy-travis"
- git config user.email "travis"
- git remote add github https://github.com/jThreeJS/jThree
- git pull github gh-pages
- git checkout gh-pages
- cd ..
install:
- npm install
script:
- npm run build -- --branch=$TRAVIS_BRANCH
- npm run doc -- --branch=$TRAVIS_BRANCH
- npm run lint -- --branch=$TRAVIS_BRANCH
- npm run cover -- --report-dir=ci/cover/$TRAVIS_BRANCH
after_script:
- cd ci
- git checkout gh-pages
- git add -A
- git commit -m "document update by travis"
- git push --force https://$GHTOKEN@github.com/jThreeJS/jThree gh-pages:gh-pages
- cd ..
language: node_js
node_js:
- 4.3.1
notifications:
  slack:
    secure: JQPxyKx9YYx0AgG2ZwFJdd3P/wEQ3HLksKgBF7IWUVwFkHifhJNRG608EiJf6JK/pJoebMt9gSJGEcTIrko3f5qlrNBdRXKvqUR57G0He84wL1QyZl4AZ5PPeesf352dr2zYKvX/TeWM5EDYuzjv4io5mgRR914hBON4GdpCOA4=
